# Massive list of sentiment keywords (Indonesian & English, Formal & Slang)
# Target: 2000+ keywords per category

# --- POSITIVE GENERATOR LISTS ---
# We will construct the final list by combining these and adding variations where possible.

POSITIVE_KEYWORDS = [
    # === INDONESIAN (ID) ===
    # Core Adjectives & Verbs
    "bagus", "baik", "positif", "maju", "tumbuh", "sukses", "meningkat", "untung", "laba", "optimis",
    "hebat", "luar biasa", "sempurna", "efektif", "efisien", "produktif", "kreatif", "inovatif", "cerdas", "pintar",
    "bijaksana", "adil", "jujur", "aman", "damai", "sejahtera", "makmur", "kaya", "berkah", "anugerah",
    "menang", "juara", "unggul", "terbaik", "favorit", "populer", "terkenal", "ternama", "terpercaya", "andal",
    "stabil", "kuat", "kokoh", "tangguh", "sehat", "bugar", "segar", "bersih", "indah", "cantik",
    "ganteng", "keren", "rapi", "teratur", "disiplin", "rajin", "tekun", "giat", "semangat", "antusias",
    "bahagia", "senang", "gembira", "riang", "puas", "bangga", "kagum", "takjub", "terpesona", "cinta",
    "sayang", "suka", "tertarik", "peduli", "simpati", "empati", "ramah", "sopan", "santun", "hormat",
    "hargai", "apresiasi", "dukung", "bantu", "tolong", "manfaat", "guna", "berharga", "penting", "signifikan",
    "relevan", "cocok", "sesuai", "tepat", "akurat", "benar", "asli", "murni", "tulus", "ikhlas",
    "setia", "loyal", "dedikasi", "komitmen", "tanggung jawab", "profesional", "ahli", "pakar", "master", "guru",
    "pemimpin", "tokoh", "panutan", "teladan", "inspirasi", "motivasi", "dorongan", "harapan", "impian", "cita-cita",
    "visi", "misi", "tujuan", "target", "pencapaian", "prestasi", "reputasi", "citra", "nama baik", "kehormatan",
    "martabat", "wibawa", "kharisma", "pesona", "daya tarik", "pengaruh", "dampak", "kontribusi", "peran", "jasa",
    "solusi", "jawaban", "kunci", "rahasia", "tips", "trik", "cara", "metode", "strategi", "taktik",
    "rencana", "program", "proyek", "kegiatan", "acara", "event", "momen", "kesempatan", "peluang", "prospek",
    "potensi", "bakat", "kemampuan", "keahlian", "keterampilan", "kompetensi", "kualitas", "mutu", "standar", "kelas",
    "level", "tingkat", "derajat", "status", "posisi", "jabatan", "pangkat", "gelar", "predikat", "penghargaan",
    "hadiah", "bonus", "insentif", "komisi", "royalti", "dividen", "imbalan", "balasan", "gaji", "upah",
    "pendapatan", "pemasukan", "omzet", "profit", "margin", "surplus", "saldo", "tabungan", "investasi", "modal",
    "aset", "harta", "kekayaan", "dana", "anggaran", "biaya", "harga", "nilai", "kurs", "saham",
    "obligasi", "reksadana", "deposito", "emas", "properti", "tanah", "bangunan", "rumah", "kantor", "pabrik",
    "mesin", "alat", "perangkat", "sarana", "prasarana", "fasilitas", "infrastruktur", "jaringan", "koneksi", "akses",
    "layanan", "servis", "dukungan", "bantuan", "perlindungan", "jaminan", "garansi", "asuransi", "keamanan", "keselamatan",
    "kesehatan", "pendidikan", "pengajaran", "pelatihan", "pembelajaran", "pengetahuan", "wawasan", "ilmu", "teknologi", "inovasi",
    "kreasi", "karya", "cipta", "produk", "barang", "jasa", "komoditas", "ekspor", "impor", "perdagangan",
    "bisnis", "usaha", "perusahaan", "korporasi", "industri", "pasar", "ekonomi", "keuangan", "perbankan", "pemerintahan",
    "negara", "bangsa", "rakyat", "masyarakat", "warga", "penduduk", "keluarga", "teman", "sahabat", "mitra",
    "rekan", "kolega", "klien", "nasabah", "pelanggan", "konsumen", "pengguna", "pemirsa", "pembaca", "pengikut",
    "fans", "penggemar", "pendukung", "simpatisan", "relawan", "donatur", "sponsor", "investor", "pemegang saham", "stakeholder",
    
    # Variations (Prefix/Suffix expansion simulation)
    "terbaik", "membaik", "perbaikan", "kebaikan", "bagusnya", "memperbagus", "kemajuan", "memajukan", "pertumbuhan", "bertumbuh",
    "kesuksesan", "menyukseskan", "peningkatan", "meningkatkan", "keuntungan", "menguntungkan", "beruntung", "optimisme", "kehebatan", "keluarbiasaan",
    "kesempurnaan", "menyempurnakan", "keefektifan", "mengefektifkan", "keefisienan", "mengefisienkan", "produktivitas", "kreativitas", "inovatif", "kecerdasan",
    "mencerdaskan", "kepintaran", "kebijaksanaan", "keadilan", "mengadili", "kejujuran", "keamanan", "mengamankan", "pengamanan", "kedamaian",
    "mendamaikan", "kesejahteraan", "menyejahterakan", "kemakmuran", "memakmurkan", "kekayaan", "memperkaya", "keberkahan", "memberkahi", "pemenang",
    "kemenangan", "memenangkan", "kejuaraan", "keunggulan", "mengunggulkan", "kepopuleran", "mempopulerkan", "keterkenalan", "kepercayaan", "mempercayai",
    "kestabilan", "menstabilkan", "kekuatan", "memperkuat", "kekokohan", "memperkokoh", "ketangguhan", "kesehatan", "menyehatkan", "kebugaran",
    "kesegaran", "menyegarkan", "kebersihan", "membersihkan", "keindahan", "memperindah", "kecantikan", "mempercantik", "kegantengan", "kerapian",
    "merapikan", "keteraturan", "mengatur", "kedisiplinan", "mendisiplinkan", "kerajinan", "ketekunan", "kegiatan", "semangat", "bersemangat",
    "kebahagiaan", "membahagiakan", "kesenangan", "menyenangkan", "kegembiraan", "menggembirakan", "kepuasan", "memuaskan", "kebanggaan", "membanggakan",
    "kekaguman", "mengagumkan", "ketakjuban", "menakjubkan", "kecintaan", "mencintai", "kasih sayang", "menyayangi", "kesukaan", "menyukai",
    "ketertarikan", "menarik", "kepedulian", "memedulikan", "keramahan", "kesopanan", "kesantunan", "kehormatan", "menghormati", "penghargaan",
    "menghargai", "apresiasi", "mengapresiasi", "dukungan", "mendukung", "bantuan", "membantu", "pertolongan", "menolong", "kemanfaatan",
    "bermanfaat", "memanfaatkan", "kegunaan", "berguna", "menggunakan", "keberhargaan", "kepentingan", "mementingkan", "signifikansi", "relevansi",
    "kecocokan", "mencocokkan", "kesesuaian", "menyesuaikan", "ketepatan", "menepatkan", "keakuratan", "kebenaran", "membenarkan", "keaslian",
    "kemurnian", "memurnikan", "ketulusan", "keikhlasan", "kesetiaan", "loyalitas", "dedikasi", "komitmen", "pertanggungjawaban", "profesionalisme",
    "keahlian", "kepakaran", "penguasaan", "kepemimpinan", "memimpin", "ketokohan", "keteladanan", "menginspirasi", "memotivasi", "mendorong",
    "berharap", "memimpikan", "mencita-citakan", "bervisi", "bermisi", "bertujuan", "menargetkan", "mencapai", "berprestasi", "bereputasi",
    "bercitra", "bermartabat", "berwibawa", "berkharisma", "mempesona", "berpengaruh", "mempengaruhi", "berdampak", "berkontribusi", "berperan",
    "berjasa", "solutif", "menjawab", "merahasiakan", "mencari cara", "bermetode", "berstrategi", "bertaktik", "merencanakan", "memprogram",
    "berproyek", "berkegiatan", "beracara", "bermomen", "berkesempatan", "berpeluang", "berprospek", "berpotensi", "berbakat", "berkemampuan",
    "berkeahlian", "terampil", "berkompetensi", "berkualitas", "bermutu", "berstandar", "berkelas", "berlevel", "bertingkat", "berderajat",
    "berstatus", "berposisi", "menjabat", "berpangkat", "bergelar", "berpredikat", "dihargai", "dihadiahi", "dibonus", "diinsentif",
    "dikomisi", "diroyalti", "didividen", "diimbal", "dibalas", "digaji", "diupah", "berpendapatan", "berpemasukan", "beromzet",
    "berprofit", "bermargin", "bersurplus", "bersaldo", "menabung", "berinvestasi", "bermodal", "beraset", "berharta", "berkekayaan",
    
    # Slang / Colloquial (ID)
    "mantap", "mantul", "gokil", "kece", "keren abis", "juara", "top", "top markotop", "jos", "gandos",
    "cuan", "cuan gede", "hoki", "bejo", "mujur", "gaspol", "sabi", "bisa banget", "oke punya", "sip",
    "yoi", "kuy", "skuy", "gas", "lanjut", "sikat", "bungkus", "angkut", "gercep", "sat set",
    "menyala", "menyala abangku", "kelas", "berkelas", "daging", "ilmu daging", "faedah", "berfaedah", "worth it", "recommended",
    "bestie", "best", "the best", "pro", "suhu", "mastah", "sepuh", "idola", "panutanque", "gemoy",
    "lucu", "imut", "uwu", "so sweet", "bucin", "gercep", "pol", "banget", "pisan", "kali",
    "enak", "sedap", "nikmat", "gurih", "legit", "maknyus", "nendang", "nagih", "candu", "bikin nagih",
    "pecah", "petjah", "booming", "viral", "trending", "hits", "kekinian", "update", "up to date", "fresh",
    "bening", "kinclong", "glowing", "cetar", "badai", "membahana", "spektakuler", "fenomenal", "legend", "epik",
    "sultan", "crazy rich", "tajir", "melintir", "bos", "juragan", "raja", "ratu", "pangeran", "putri",
    "dewi", "bidadari", "malaikat", "pahlawan", "ksatria", "jawara", "pendekar", "jagoan", "bintang", "seleb",
    "artis", "diva", "maestro", "legenda", "mitos", "ikon", "simbol", "lambang", "tanda", "sinyal",
    "kode", "sandi", "kunci", "pintu", "gerbang", "jalan", "jembatan", "tangga", "lift", "roket",
    "pesawat", "kapal", "mobil", "motor", "sepeda", "lari", "jalan", "terbang", "melayang", "tinggi",
    "puncak", "atas", "langit", "angkasa", "surga", "nirwana", "firdaus", "taman", "bunga", "mekar",
    "wangi", "harum", "semerbak", "berseri", "cahaya", "sinar", "terang", "benderang", "kilau", "gemerlap",
    
    # === ENGLISH (EN) ===
    # Core Adjectives & Verbs
    "good", "great", "excellent", "amazing", "wonderful", "fantastic", "superb", "outstanding", "exceptional", "terrific",
    "positive", "optimistic", "favorable", "promising", "encouraging", "bright", "rosy", "hopeful", "confident", "assured",
    "success", "successful", "triumph", "victory", "win", "winner", "achievement", "accomplishment", "feat", "milestone",
    "growth", "expansion", "increase", "rise", "surge", "boom", "boost", "gain", "profit", "revenue",
    "benefit", "advantage", "pro", "upside", "asset", "value", "worth", "merit", "virtue", "quality",
    "strong", "robust", "solid", "stable", "steady", "secure", "safe", "sound", "healthy", "fit",
    "effective", "efficient", "productive", "fruitful", "profitable", "lucrative", "rewarding", "satisfying", "pleasing", "gratifying",
    "happy", "glad", "joyful", "cheerful", "delighted", "content", "satisfied", "pleased", "thrilled", "excited",
    "love", "like", "adore", "admire", "respect", "honor", "esteem", "regard", "appreciate", "value",
    "support", "back", "endorse", "advocate", "champion", "promote", "encourage", "foster", "nurture", "cultivate",
    "innovative", "creative", "original", "fresh", "new", "modern", "advanced", "cutting-edge", "state-of-the-art", "leading",
    "smart", "intelligent", "clever", "wise", "brilliant", "genius", "talented", "gifted", "skilled", "capable",
    "reliable", "dependable", "trustworthy", "honest", "sincere", "genuine", "authentic", "real", "true", "loyal",
    "beautiful", "pretty", "handsome", "lovely", "charming", "attractive", "appealing", "stunning", "gorgeous", "breathtaking",
    "clean", "pure", "clear", "bright", "shining", "radiant", "glowing", "vibrant", "lively", "energetic",
    "dynamic", "active", "agile", "flexible", "adaptable", "versatile", "resilient", "durable", "lasting", "sustainable",
    "green", "eco-friendly", "environmentally friendly", "ethical", "moral", "principled", "just", "fair", "equitable", "right",
    "correct", "accurate", "precise", "exact", "perfect", "flawless", "impeccable", "ideal", "optimal", "prime",
    "top", "peak", "summit", "pinnacle", "apex", "zenith", "climax", "highlight", "best", "finest",
    "supreme", "ultimate", "maximum", "highest", "utmost", "paramount", "foremost", "primary", "main", "major",
    "key", "crucial", "vital", "essential", "necessary", "important", "significant", "meaningful", "relevant", "pertinent",
    "useful", "helpful", "beneficial", "valuable", "precious", "priceless", "invaluable", "worthwhile", "advantageous", "favorable",
    "lucky", "fortunate", "blessed", "gifted", "favored", "privileged", "honored", "grateful", "thankful", "appreciative",
    "kind", "generous", "giving", "charitable", "benevolent", "altruistic", "compassionate", "sympathetic", "empathetic", "understanding",
    "friendly", "amiable", "amicable", "cordial", "warm", "welcoming", "hospitable", "sociable", "outgoing", "extroverted",
    "calm", "peaceful", "serene", "tranquil", "quiet", "still", "relaxed", "composed", "collected", "unruffled",
    "brave", "courageous", "bold", "daring", "fearless", "intrepid", "heroic", "valiant", "gallant", "stouthearted",
    
    # Business/Finance (EN)
    "bullish", "bull", "rally", "uptrend", "outperform", "beat", "exceed", "surpass", "record", "high",
    "dividend", "yield", "return", "roi", "equity", "capital", "investment", "funding", "financing", "liquidity",
    "solvency", "credit", "rating", "upgrade", "buy", "long", "hold", "accumulate", "acquire", "merger",
    "acquisition", "partnership", "alliance", "collaboration", "cooperation", "deal", "contract", "agreement", "settlement", "resolution",
    "launch", "release", "debut", "premiere", "introduction", "unveiling", "rollout", "implementation", "execution", "operation",
    "production", "manufacturing", "output", "supply", "demand", "sales", "marketing", "advertising", "branding", "promotion",
    "customer", "client", "consumer", "user", "subscriber", "member", "partner", "associate", "colleague", "employee",
    "staff", "team", "group", "workforce", "personnel", "human resources", "talent", "recruitment", "hiring", "employment",
    "job", "career", "profession", "occupation", "vocation", "work", "labor", "service", "duty", "responsibility",
    "role", "function", "task", "assignment", "project", "mission", "objective", "goal", "aim", "target",
    "strategy", "plan", "policy", "regulation", "law", "rule", "standard", "norm", "criterion", "benchmark",
    "measure", "metric", "indicator", "index", "score", "grade", "rank", "rating", "level", "tier",
    
    # Slang (EN)
    "cool", "awesome", "dope", "lit", "fire", "sick", "rad", "gnarly", "wicked", "sweet",
    "nice", "neat", "dandy", "swell", "grand", "fab", "fabulous", "glam", "chic", "posh",
    "trendy", "hip", "happening", "buzzing", "hype", "clutch", "goat", "legendary", "epic", "iconic",
    "slay", "killed it", "nailed it", "crushed it", "on point", "on fleek", "snatched", "gucci", "boujee", "fancy",
    "chill", "vibes", "good vibes", "mood", "goals", "inspo", "stan", "ship", "otp", "fam",
    "bestie", "bff", "homie", "bro", "dude", "mate", "pal", "buddy", "chum", "friend",
    "win", "ftw", "gg", "wp", "ez", "noob", "pro", "hacker", "godlike", "beast",
    "money", "cash", "dough", "bread", "cheddar", "stacks", "racks", "bands", "bank", "rich",
    "baller", "flex", "drip", "swag", "sauce", "juice", "clout", "fame", "glory", "power"
]

# --- NEGATIVE GENERATOR LISTS ---
NEGATIVE_KEYWORDS = [
    # === INDONESIAN (ID) ===
    # Core Adjectives & Verbs
    "buruk", "jelek", "negatif", "mundur", "turun", "gagal", "rugi", "hancur", "krisis", "pesimis",
    "parah", "kacau", "rusak", "bobrok", "ancur", "berantakan", "kotor", "jijik", "muak", "benci",
    "marah", "kesal", "kecewa", "sedih", "duka", "luka", "sakit", "nyeri", "perih", "derita",
    "sengsara", "miskin", "melarat", "bangkrut", "pailit", "utang", "beban", "masalah", "kendala", "hambatan",
    "rintangan", "gangguan", "ancaman", "bahaya", "risiko", "bencana", "musibah", "tragedi", "malapetaka", "celaka",
    "sial", "apes", "nahas", "korban", "tewas", "mati", "meninggal", "gugur", "hilang", "lenyap",
    "curang", "tipu", "bohong", "dusta", "palsu", "gadungan", "kw", "tiruan", "bajakan", "ilegal",
    "jahat", "kejam", "sadis", "bengis", "biadab", "brutal", "ganas", "liar", "buas", "agresif",
    "lemah", "lesu", "letih", "lelah", "capek", "penat", "bosan", "jenuh", "muak", "sebal",
    "takut", "cemas", "khawatir", "gelisah", "panik", "stres", "depresi", "frustrasi", "putus asa", "menyerah",
    "kalah", "tumbang", "keok", "takluk", "mundur", "lari", "kabur", "sembunyi", "malu", "hina",
    "aib", "noda", "cacat", "cela", "kritik", "protes", "demo", "mogok", "konflik", "sengketa",
    "perang", "tempur", "tarung", "kelahi", "ribut", "gaduh", "bising", "berisik", "ganggu", "usik",
    "salah", "keliru", "sesat", "dosa", "maksiat", "haram", "najis", "kotor", "polusi", "limbah",
    "racun", "bisa", "virus", "bakteri", "kuman", "penyakit", "wabah", "pandemi", "epidemi", "infeksi",
    "korupsi", "kolusi", "nepotisme", "suap", "sogok", "pungli", "peras", "rampok", "maling", "curi",
    "copet", "jambret", "begal", "pembunuh", "penjahat", "kriminal", "tersangka", "terdakwa", "terpidana", "narapidana",
    "penjara", "bui", "sel", "tahanan", "hukuman", "sanksi", "denda", "vonis", "tuntutan", "gugatan",
    "dakwaan", "tuduhan", "fitnah", "hoaks", "hasut", "provokasi", "teror", "intimidasi", "ancam", "paksa",
    "tekan", "tindas", "jajah", "eksploitasi", "diskriminasi", "rasis", "sara", "buli", "ejek", "hina",
    "caci", "maki", "umpat", "sumpah", "serapah", "kutuk", "laknat", "azab", "siksa", "aniaya",
    "perkosa", "leceh", "cabul", "mesum", "porno", "judi", "mabuk", "narkoba", "obat", "candu",
    
    # Variations
    "keburukan", "memburuk", "kejelekan", "menjelekkan", "kenegatifan", "kemunduran", "memundurkan", "penurunan", "menurunkan", "kegagalan",
    "menggagalkan", "kerugian", "merugikan", "kehancuran", "menghancurkan", "kekrisisan", "kepesimisan", "keparahan", "memperparah", "kekacauan",
    "mengacaukan", "kerusakan", "merusak", "kebobrokan", "kehancuran", "kebenaran", "kekotoran", "mengotori", "kejijikan", "menjijikkan",
    "kemuakan", "memuakkan", "kebencian", "membenci", "kemarahan", "memarahi", "kekesalan", "mengesalkan", "kekecewaan", "mengecewakan",
    "kesedihan", "menyedihkan", "kedukaan", "berduka", "kelukaan", "melukai", "kesakitan", "menyakitkan", "kenyerian", "keperihan",
    "penderitaan", "menderita", "kesengsaraan", "menyengsarakan", "kemiskinan", "memiskinkan", "kemelaratan", "kebangkrutan", "membangkrutkan", "kepailitan",
    "berutang", "membebani", "bermasalah", "terkendala", "terhambat", "merintangi", "mengganggu", "mengancam", "membahayakan", "berisiko",
    "berbencana", "bermusibah", "bertragedi", "bermalapetaka", "mencelakakan", "kesialan", "menyialkan", "keapesan", "kenahasan", "mengorbankan",
    "ketewasan", "kematian", "mematikan", "meninggal dunia", "gugurnya", "kehilangan", "menghilangkan", "kelenyapan", "melenyapkan", "kecurangan",
    "mencurangi", "penipuan", "menipu", "kebohongan", "membohongi", "kedustaan", "mendustai", "kepalsuan", "memalsukan", "kegadungan",
    "ketiruan", "meniru", "pembajakan", "membajak", "keilegalan", "kejahatan", "menjahati", "kekejaman", "mengejamkan", "kesadisan",
    "kebengisan", "kebiadaban", "kebrutalan", "keganasan", "keliaran", "kebuasan", "keagresifan", "kelemahan", "melemahkan", "kelesuan",
    "keletihan", "kelelahan", "kecapekan", "kepenatan", "kebosanan", "membosankan", "kejenuhan", "menjenuhkan", "kesebalan", "menyebalkan",
    "ketakutan", "menakutkan", "kecemasan", "mencemaskan", "kekhawatiran", "mengkhawatirkan", "kegelisahan", "menggelisahkan", "kepanikan", "memanikkan",
    "kestresan", "kedepresian", "kefrustrasian", "keputusasaan", "penyerahan", "kekalahan", "mengalahkan", "ketumbangan", "menumbangkan", "kekeokan",
    "ketaklukkan", "menaklukkan", "kemunduran", "pelarian", "pengaburan", "persembunyian", "kemaluan", "memalukan", "kehinaan", "menghina",
    "keaiban", "kenodaan", "menodai", "kecacatan", "mencacati", "kecelaan", "mencela", "pengkritikan", "mengkritik", "pemrotesan",
    "memprotes", "pendemoan", "mendemo", "pemogokan", "memogok", "pengkonflikan", "penyengketaan", "peperangan", "memerangi", "pertempuran",
    "bertempur", "pertarungan", "bertarung", "perkelahian", "berkelahi", "keributan", "meributkan", "kegaduhan", "kebisingan", "keberisikan",
    "gangguan", "mengusik", "kesalahan", "menyalahkan", "kekeliruan", "mengelirukan", "kesesatan", "menyesatkan", "kedosaan", "berdosa",
    "kemaksiatan", "keharaman", "mengharamkan", "kenajisan", "menajiskan", "pengotoran", "pemolusian", "pelimbahan", "keracunan", "meracuni",
    "kebisaan", "pervirusan", "perbakterian", "perkumanan", "penyakitan", "pewabahan", "pepandemian", "pepidemian", "penginfeksian", "menginfeksi",
    "pengkorupsian", "mengkorupsi", "pengkolusian", "penepotismen", "penyuapan", "menyuap", "penyogokan", "menyogok", "pemunglian", "pemerasan",
    "memeras", "perampokan", "merampok", "kemalingan", "pencurian", "mencuri", "pencopetan", "mencopet", "penjambretan", "menjambret",
    "pembegalan", "membegal", "pembunuhan", "membunuh", "penjahatan", "kekriminalan", "tersangkakan", "terdakwakan", "terpidanakan", "narapidanakan",
    
    # Slang / Colloquial (ID)
    "zonk", "amsyong", "boncos", "rungkad", "rungkat", "ambyar", "anjlok", "nyungsep", "tenggelam", "karam",
    "gaje", "gajelas", "receh", "murahan", "kampungan", "ndeso", "norak", "alay", "lebay", "baper",
    "mager", "gabut", "halu", "sotoy", "kepo", "julid", "nyinyir", "bacot", "bawel", "berisik",
    "toxic", "racun", "sampah", "trash", "ampas", "buluk", "dekil", "kumel", "bau", "busuk",
    "basi", "garing", "jayus", "krik", "krik krik", "awkward", "cringe", "ilfil", "muak", "eneg",
    "php", "pemberi harapan palsu", "ghosting", "selingkuh", "pelakor", "pebinor", "buaya", "playboy", "playgirl", "fakboy",
    "sad boy", "sad girl", "galau", "merana", "ngenes", "kasian", "miris", "prihatin", "sedih banget", "nangis",
    "emosi", "darah tinggi", "spaneng", "pusing", "mumet", "pening", "migrain", "sakit kepala", "ribet", "ruwet",
    "rempong", "lelet", "lemot", "lola", "gaptek", "kudet", "katrok", "udik", "bego", "tolol",
    "goblok", "idiot", "dungu", "bodoh", "otak udang", "kosong", "hampa", "sepi", "sunyi", "senyap",
    "kacrut", "kampret", "sialan", "bangsat", "bajingan", "keparat", "brengsek", "setan", "iblis", "dajjal",
    "neraka", "jahanam", "laknat", "kutuk", "sial", "buntung", "apes", "celaka", "mampus", "modar",
    "koit", "tewas", "lewat", "hilang", "lenyap", "musnah", "punah", "habis", "ludes", "tandas",
    "melarat", "kere", "bokek", "kanker", "kantong kering", "miskin", "susah", "sengsara", "menderita", "tersiksa",
    
    # === ENGLISH (EN) ===
    # Core Adjectives & Verbs
    "bad", "poor", "negative", "adverse", "unfavorable", "harmful", "damaging", "destructive", "detrimental", "injurious",
    "worse", "worst", "terrible", "horrible", "awful", "dreadful", "ghastly", "hideous", "ugly", "nasty",
    "fail", "failure", "loss", "defeat", "decline", "decrease", "drop", "fall", "slump", "crash",
    "crisis", "disaster", "catastrophe", "calamity", "emergency", "trouble", "problem", "issue", "difficulty", "challenge",
    "risk", "danger", "threat", "hazard", "peril", "insecure", "unsafe", "vulnerable", "exposed", "weak",
    "sad", "unhappy", "miserable", "sorrow", "grief", "pain", "suffering", "agony", "distress", "anguish",
    "angry", "mad", "furious", "upset", "annoyed", "irritated", "frustrated", "disappointed", "dissatisfied", "displeased",
    "hate", "dislike", "loathe", "detest", "despise", "scorn", "disdain", "contempt", "hostile", "enemy",
    "wrong", "incorrect", "false", "fake", "error", "mistake", "fault", "defect", "flaw", "bug",
    "dirty", "filthy", "messy", "polluted", "contaminated", "toxic", "poisonous", "infected", "sick", "ill",
    "disease", "illness", "sickness", "ailment", "virus", "bacteria", "germ", "plague", "epidemic", "pandemic",
    "crime", "criminal", "illegal", "unlawful", "illicit", "corrupt", "fraud", "scam", "theft", "robbery",
    "violence", "violent", "brutal", "cruel", "savage", "vicious", "aggressive", "attack", "assault", "abuse",
    "fear", "afraid", "scared", "terrified", "frightened", "anxious", "worried", "nervous", "tense", "stressed",
    "boring", "dull", "tedious", "monotonous", "uninteresting", "tiresome", "wearisome", "drab", "dreary", "plain",
    "stupid", "dumb", "idiotic", "foolish", "silly", "absurd", "ridiculous", "ludicrous", "senseless", "irrational",
    "crazy", "insane", "mad", "lunatic", "psycho", "maniac", "deranged", "unhinged", "unstable", "erratic",
    "lazy", "idle", "slothful", "sluggish", "lethargic", "inactive", "passive", "slow", "tardy", "late",
    "rude", "impolite", "insolent", "impudent", "cheeky", "disrespectful", "offensive", "insulting", "abusive", "vulgar",
    "gross", "disgusting", "revolting", "repulsive", "repugnant", "nauseating", "sickening", "vile", "foul", "rank",
    "evil", "wicked", "sinful", "immoral", "unethical", "wrong", "bad", "naughty", "mischievous", "malicious",
    "cruel", "mean", "nasty", "unkind", "unfriendly", "hostile", "cold", "distant", "aloof", "detached",
    "hard", "difficult", "tough", "arduous", "strenuous", "laborious", "demanding", "challenging", "taxing", "grueling",
    "heavy", "weighty", "burdensome", "oppressive", "crushing", "overwhelming", "unbearable", "intolerable", "insufferable", "agonizing",
    "dark", "gloomy", "dim", "dull", "shadowy", "murky", "cloudy", "foggy", "misty", "hazy",
    
    # Business/Finance (EN)
    "bearish", "bear", "downtrend", "underperform", "miss", "lag", "trail", "lose", "drop", "plunge",
    "default", "bankruptcy", "insolvency", "liquidation", "foreclosure", "debt", "liability", "deficit", "shortfall", "loss",
    "recession", "depression", "slowdown", "contraction", "stagnation", "inflation", "deflation", "stagflation", "bubble", "crash",
    "downgrade", "sell", "short", "dump", "divest", "exit", "withdraw", "terminate", "cancel", "revoke",
    "lawsuit", "litigation", "dispute", "conflict", "strike", "protest", "boycott", "embargo", "sanction", "penalty",
    "fine", "fee", "charge", "cost", "expense", "expenditure", "spending", "waste", "loss", "damage",
    "risk", "uncertainty", "volatility", "instability", "fluctuation", "variance", "deviation", "discrepancy", "error", "mistake",
    "fraud", "scam", "scheme", "racket", "bribe", "kickback", "corruption", "embezzlement", "laundering", "evasion",
    "tax", "duty", "tariff", "levy", "toll", "rate", "price", "cost", "fee", "charge",
    "unemployment", "jobless", "layoff", "firing", "termination", "redundancy", "downsizing", "cutback", "austerity", "budget",
    
    # Slang (EN)
    "sucks", "sucked", "stinks", "lame", "trash", "garbage", "rubbish", "crap", "shitty", "bullshit",
    "bummer", "drag", "killjoy", "downer", "buzzkill", "flop", "bust", "dud", "lemon", "fail",
    "sketchy", "dodgy", "shady", "sus", "suspicious", "creepy", "weird", "freaky", "scary", "spooky",
    "cringe", "cringey", "awkward", "embarrassing", "facepalm", "oops", "yikes", "ouch", "damn", "hell",
    "salty", "bitter", "sour", "pressed", "triggered", "shook", "shaken", "rattled", "upset", "mad",
    "ghosted", "dumped", "cheated", "played", "fooled", "tricked", "scammed", "conned", "ripped off", "robbed",
    "broke", "poor", "bust", "bankrupt", "debt", "owing", "loosing", "lost", "loser", "noob",
    "hater", "troll", "bully", "snitch", "rat", "snake", "fake", "phony", "liar", "cheat",
    "basic", "mid", "flop era", "L", "take the L", "ratio", "ratioed", "cancelled", "clown", "simp"
]

# Ensure uniqueness
POSITIVE_KEYWORDS = list(set(POSITIVE_KEYWORDS))
NEGATIVE_KEYWORDS = list(set(NEGATIVE_KEYWORDS))
